create table public.client_error_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  occurred_at timestamptz not null default now(),
  route text not null,
  source text not null,
  message text not null,
  release text,
  metadata jsonb not null default '{}'::jsonb,
  constraint client_error_events_route_length check (length(route) between 1 and 256),
  constraint client_error_events_source check (
    source in ('REACT_BOUNDARY', 'WINDOW_ERROR', 'UNHANDLED_REJECTION')
  ),
  constraint client_error_events_message_length check (length(message) between 1 and 1000),
  constraint client_error_events_release_length check (
    release is null or length(release) <= 100
  ),
  constraint client_error_events_metadata_object check (jsonb_typeof(metadata) = 'object'),
  constraint client_error_events_metadata_size check (octet_length(metadata::text) <= 4000)
);

comment on table public.client_error_events is
  'Sanitized client-side failures reported by authenticated users for production support.';

create index client_error_events_occurred_at_idx
  on public.client_error_events (occurred_at desc);
create index client_error_events_user_occurred_at_idx
  on public.client_error_events (user_id, occurred_at desc);

alter table public.client_error_events enable row level security;

create policy client_error_events_read_operations
on public.client_error_events
for select
to authenticated
using (
  (select private.has_role('PORTFOLIO_MANAGER'::public.app_role))
  or (select private.has_role('ADMIN'::public.app_role))
);

revoke all on table public.client_error_events from public, anon, authenticated;
grant select on table public.client_error_events to authenticated;

create or replace function public.report_client_error(
  error_source text,
  error_message text,
  error_route text,
  app_release text default null,
  error_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  normalized_source text := upper(trim(error_source));
  created_id bigint;
begin
  if actor is null then
    raise exception 'Requiere una sesión autenticada' using errcode = 'P0001';
  end if;

  if normalized_source not in ('REACT_BOUNDARY', 'WINDOW_ERROR', 'UNHANDLED_REJECTION') then
    raise exception 'Fuente de error no válida' using errcode = 'P0001';
  end if;

  if nullif(trim(error_message), '') is null or length(trim(error_message)) > 1000 then
    raise exception 'Mensaje de error no válido' using errcode = 'P0001';
  end if;

  if nullif(trim(error_route), '') is null or length(trim(error_route)) > 256 then
    raise exception 'Ruta de error no válida' using errcode = 'P0001';
  end if;

  if app_release is not null and length(trim(app_release)) > 100 then
    raise exception 'Versión de aplicación no válida' using errcode = 'P0001';
  end if;

  if jsonb_typeof(coalesce(error_metadata, '{}'::jsonb)) <> 'object'
     or octet_length(coalesce(error_metadata, '{}'::jsonb)::text) > 4000 then
    raise exception 'Metadatos de error no válidos' using errcode = 'P0001';
  end if;

  if (
    select count(*)
    from public.client_error_events event
    where event.user_id = actor
      and event.occurred_at >= now() - interval '5 minutes'
  ) >= 10 then
    return jsonb_build_object('accepted', false, 'reason', 'RATE_LIMITED');
  end if;

  insert into public.client_error_events (
    user_id, route, source, message, release, metadata
  ) values (
    actor,
    trim(error_route),
    normalized_source,
    trim(error_message),
    nullif(trim(app_release), ''),
    coalesce(error_metadata, '{}'::jsonb)
  )
  returning id into created_id;

  return jsonb_build_object('accepted', true, 'event_id', created_id);
end
$$;

revoke all on function public.report_client_error(text, text, text, text, jsonb)
  from public, anon;
grant execute on function public.report_client_error(text, text, text, text, jsonb)
  to authenticated;
